language: python
python:
  - "3.6"

services:
  - docker

before_install: cd logisticsnetwork

before_script: pip install docker-compose

script:
  - docker-compose exec logistics-api su -c "python manage.py test"
