language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - cd logisticsnetwork
  - docker container rm $(docker container ls -qa)
  - docker build -f Dockerfile -t logistics-api .
  - pkill postgres

before_script: pip install docker-compose

script:
  - docker-compose run logistics-api su -c "python manage.py test"
