language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run logistics-api sh -c "pip install -r /logisticsnetwork/requirements.txt && python /logisticsnetwork/manage.py test"

