language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

install: pip install -r /logisticsnetwork/requirements.txt

script:
  - docker-compose run logistics-api sh -c "python /logistics-api/logisticsnetwork/manage.py test"

