language: python
python:
  - "3.6"

services:
  - docker

before_script:
  - cd /logisticsnetwork
  - pip install docker-compose

script:
  - docker-compose run logistics-api sh -c "pip install -r requirements.txt && python manage.py test"

