language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - cd logisticsnetwork
  - docker build -f Dockerfile -t logistics-api .

before_script: pip install docker-compose

script:
  - docker-compose run logistics-api su -c "python manage.py test"
