# Generated by Django 2.1.8 on 2019-04-22 04:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('path_data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='path_data')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
            ],
            options={
                'verbose_name': 'Logistic Network',
            },
        ),
    ]
