# Generated by Django 2.1.8 on 2019-04-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticsnet',
            name='state',
        ),
    ]
