version: '2'

services:
  logistics-api:
    build: .
    command: su -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
       - "8000:8000"
    depends_on:
       - postgres
    links:
      - db
    volumes:
      - .:/logisticsnetwork

  postgres:
    image: postgres:10.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=logistics
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
